### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by weado** [FreeTHX/pyremora#1]
Hello,
I have a remora and I'm starting to use HA. I installed pyremora on my HA, with the pip install pyremora command line, but I don't know how can I do use it in HA ?
May you help me (and others personn too I hope) to configure your HA add-on ?
Thank you !

**Comment by FreeTHX** [comment]
Hi @weado

I will soon (next week ?) publish a custom component for HA, including Remora TeleInfo sensor and Remora FilPilote climate.
Stay tuned ! ;)

**Comment by weado** [comment]
Great !!!  I look forward to see that !

**Comment by FreeTHX** [comment]
Et voila !
https://github.com/FreeTHX/remora-ha
I let you try and give me a feedback.
I will post it on the Remora Community forum (in french)
